services:
  onnx:
    build:
      context: .
      dockerfile: openvino-cpu.Dockerfile
    command: [
       "--model-en", "nemo-parakeet-tdt-0.6b-v2",
      "--uri", "tcp://0.0.0.0:10300"
    ]
    volumes:
      - ./local:/data
      - ./cache:/cache
    restart: unless-stopped
    ports:
      - "10300:10300"